/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lexicon.generator.ui;

import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lexicon.generator.objects.LexiconObject;
import lexicon.generator.storage.Storage;

/**
 *
 * @author akenu
 */
public class LexiconUI extends javax.swing.JFrame {

    private LexiconObject lo = null;
    /**
     * Creates new form LexiconUI
     */
    public LexiconUI() {
        initComponents();
        this.lo = new LexiconObject();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDefinition = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMeaning = new javax.swing.JTextArea();
        jAddDefinition = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jBBCode = new javax.swing.JTextArea();
        jGenerateBB = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDefinitionList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jSaveMenu = new javax.swing.JMenuItem();
        jLoadMenu = new javax.swing.JMenuItem();
        jAboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lexicon Generator");

        jLabel1.setText("Add new definition");

        jMeaning.setColumns(20);
        jMeaning.setRows(5);
        jScrollPane1.setViewportView(jMeaning);

        jAddDefinition.setText("Add definition");
        jAddDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddDefinitionActionPerformed(evt);
            }
        });

        jBBCode.setColumns(20);
        jBBCode.setRows(5);
        jScrollPane2.setViewportView(jBBCode);

        jGenerateBB.setText("Generate BB code");
        jGenerateBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateBBActionPerformed(evt);
            }
        });

        jDefinitionList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jDefinitionList);

        jFileMenu.setText("File");

        jSaveMenu.setText("Save");
        jSaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveMenuActionPerformed(evt);
            }
        });
        jFileMenu.add(jSaveMenu);

        jLoadMenu.setText("Load");
        jLoadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadMenuActionPerformed(evt);
            }
        });
        jFileMenu.add(jLoadMenu);

        jAboutMenu.setText("About");
        jAboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAboutMenuActionPerformed(evt);
            }
        });
        jFileMenu.add(jAboutMenu);

        jMenuBar1.add(jFileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddDefinition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jGenerateBB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddDefinition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGenerateBB))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveMenuActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        if(jFileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jFileChooser.getSelectedFile();
            Storage storage = new Storage(lo);
            storage.save(selectedFile);
            
            JOptionPane.showMessageDialog(this, "Data saved");
        }
    }//GEN-LAST:event_jSaveMenuActionPerformed

    private void jAddDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddDefinitionActionPerformed
        
        
        String definition = jDefinition.getText();
        String meaning = jMeaning.getText();
        
        lo.addDefinition(definition, meaning);
        JOptionPane.showMessageDialog(this, "Definition added");
        jDefinition.setText("");
        jMeaning.setText("");
        this.reloadDefinitions();
    }//GEN-LAST:event_jAddDefinitionActionPerformed

    private void reloadDefinitions() {
        Set keySet = this.lo.getTreemap().keySet();
        DefaultListModel<Object> dlm = new DefaultListModel<>();
        for(Object key : keySet) {
            dlm.addElement(key);
        }
        
        this.jDefinitionList.setModel(dlm);
    }
    
    private void jGenerateBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateBBActionPerformed
        String bbCode = lo.getBBCode();
        jBBCode.setText(bbCode);
        JOptionPane.showMessageDialog(this, "BB Code generated");
    }//GEN-LAST:event_jGenerateBBActionPerformed

    private void jLoadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadMenuActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        if(jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser.getSelectedFile();
            
            Storage storage = new Storage(lo);
            this.lo = storage.load(f);
            
            JOptionPane.showMessageDialog(this, "Data loaded");
            this.reloadDefinitions();
        }
        
    }//GEN-LAST:event_jLoadMenuActionPerformed

    private void jAboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAboutMenuActionPerformed
        JOptionPane.showMessageDialog(this, "Lexicon Generator, written by Frater Akenu", "Lexicon Generator: About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jAboutMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LexiconUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LexiconUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LexiconUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LexiconUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LexiconUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAboutMenu;
    private javax.swing.JButton jAddDefinition;
    private javax.swing.JTextArea jBBCode;
    private javax.swing.JTextField jDefinition;
    private javax.swing.JList jDefinitionList;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JButton jGenerateBB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jLoadMenu;
    private javax.swing.JTextArea jMeaning;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jSaveMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
